//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketTrackerEntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Performance
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Performance()
        {
            this.Tickets = new HashSet<Ticket>();
        }
    
        public int PerformanceId { get; set; }
        public int ShowId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<decimal> ChangeCollected { get; set; }
        public Nullable<decimal> OnesCollected { get; set; }
        public Nullable<decimal> FivesCollected { get; set; }
        public Nullable<decimal> TensCollected { get; set; }
        public Nullable<decimal> TwentiesCollected { get; set; }
        public Nullable<decimal> FiftiesCollected { get; set; }
        public Nullable<decimal> HundredsCollected { get; set; }
        public Nullable<decimal> CheckAmount { get; set; }
        public Nullable<decimal> CreditCardAmount { get; set; }
        public Nullable<decimal> StartingCash { get; set; }
        public Nullable<int> ClassPasses { get; set; }
        public Nullable<decimal> StarVoucherAmount { get; set; }
        public Nullable<decimal> ConcessionVoucherAmount { get; set; }
        public Nullable<decimal> Donations { get; set; }
        public Nullable<decimal> Miscellaneous { get; set; }
        public Nullable<decimal> CreditCardFees { get; set; }
        public Nullable<int> SeasonPasses { get; set; }
    
        public virtual Show Show { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ticket> Tickets { get; set; }
    }
}
